### ISSUE TITLE
Issue with Tag2Text during setup

### ISSUE THREAD

**Issue by agi-codes** [QianWangX/InstructEdit#4]
I'm encountering an issue with the Tag2Text submodule. According to the setup guide, Tag2Text should be installed via the git submodule update --init --recursive command. However, after running this command, the Tag2Text directory doesn't seem to be populated, and subsequently, the cd Tag2Text && pip install -r requirements.txt command fails with "No such file or directory".

Here are the steps I've taken to troubleshoot:
Checked for a .gitmodules file in the root directory of the repository.
Ran git submodule status from the root of the parent repository.
Inspected the structure of the repository to ensure it is cloned correctly.

Unfortunately, I'm still facing the same issue. Could you please provide any guidance or insights that might help resolve this problem? Thanks in advance!

**Comment by QianWangX** [comment]
Hi @agi-codes , could you try to skip Tag2Text? I think this submodule is not really necessary to get the notebook run correctly.
