### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by hjhyunjinkim** [QianWangX/InstructEdit#6]
Hi I'm using your notebook demo for further experiments, and I keep encountering this error 

```
Cell In[4], line 55, in get_grounding_output(model, image, caption, box_threshold, text_threshold, with_logits, device, return_max)
     52         pred_phrases.append(pred_phrase)
     54 if return_max:
---> 55     max_logit_index, max_logit = max(enumerate(logits_filt_item), key=itemgetter(1))
     56     return boxes_filt[max_logit_index].unsqueeze(0), [pred_phrases[max_logit_index]]
     58 return boxes_filt, pred_phrases

ValueError: max() arg is an empty sequence
```

Do you know why this is happening?
The image i used is the cat_dog image, and I set `user_instructions = "Change the cat to dog"`.

**Comment by QianWangX** [comment]
Hi @hjhyunjinkim , sorry for the late reply. I couldn't reproduce this issue, but I think that error means the Grounding DINO didn't detect anything so there was no bounding box. Did you correctly download the DINO checkpoint and set it up? Or can you check in the cell output that if the generated segmentation prompt is something meaningful, for example, "cat"?
